# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_auto_20171103_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('fe_de_bautizo', models.BooleanField()),
                ('partida_de_nacimiento', models.BooleanField()),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Area')),
                ('id_catequista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Catequista')),
                ('id_catequizando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Catequizando')),
                ('id_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Comunidad')),
            ],
        ),
    ]
