# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0009_auto_20171103_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('fe_de_bautizo', models.BooleanField()),
                ('partida_de_nacimiento', models.BooleanField()),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Catequista',
            fields=[
                ('id_catequista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('usename', models.CharField(max_length=12, unique=True)),
                ('contra', models.CharField(max_length=20)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Area')),
                ('id_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Comunidad')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_catequista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Catequista'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_catequizando',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Catequizando'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Comunidad'),
        ),
    ]
