# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0010_auto_20171103_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catequista',
            old_name='usename',
            new_name='username',
        ),
    ]
