# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0011_auto_20171107_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_catequizando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Catequizando')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Area')),
            ],
        ),
        migrations.RenameField(
            model_name='catequista',
            old_name='contra',
            new_name='password',
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_catequista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Catequista'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Comunidad'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Grupo'),
        ),
        migrations.AddField(
            model_name='catequizando',
            name='id_grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Grupo'),
            preserve_default=False,
        ),
    ]
