# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0012_auto_20171107_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catequizando',
            name='fecha_de_bautizo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='catequizando',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
    ]
