# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0013_auto_20171109_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catequizando',
            name='fecha_de_bautizo',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='catequizando',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
