# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0014_auto_20171109_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='id_catequista',
        ),
        migrations.AddField(
            model_name='catequista',
            name='id_grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catequizando',
            name='id_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Grupo'),
        ),
    ]
