# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 09:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripcion', '0015_auto_20171111_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catequista',
            options={'verbose_name': 'Catequista', 'verbose_name_plural': 'Catequistas'},
        ),
        migrations.AlterModelManagers(
            name='catequista',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='catequista',
            name='email',
        ),
        migrations.RemoveField(
            model_name='catequista',
            name='password',
        ),
        migrations.RemoveField(
            model_name='catequista',
            name='username',
        ),
        migrations.AddField(
            model_name='catequista',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='id_catequizando',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inscripcion.Catequizando'),
        ),
        migrations.AlterField(
            model_name='catequista',
            name='id_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Grupo'),
        ),
        migrations.AlterField(
            model_name='catequizando',
            name='id_grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inscripcion.Grupo'),
            preserve_default=False,
        ),
    ]
