# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-25 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripcion', '0018_auto_20171121_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catequista',
            options={},
        ),
        migrations.AlterModelManagers(
            name='catequista',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='catequista',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='catequista',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='catequizando',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Grupo'),
        ),
    ]
