# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0019_auto_20171124_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='catequista',
            name='is_Admin',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catequista',
            name='is_Coordinador',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catequista',
            name='id_comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Comunidad'),
            preserve_default=False,
        ),
    ]
