# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0020_auto_20171125_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
