# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0022_auto_20171201_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='catequista',
            name='is_Secretaria',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
