# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('fe_de_bautizo', models.BooleanField()),
                ('partida_de_nacimiento', models.BooleanField()),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Area')),
            ],
        ),
        migrations.AddField(
            model_name='catequista',
            name='usename',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_catequista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Catequista'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_catequizando',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Catequizando'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Comunidad'),
        ),
    ]
