# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_auto_20171102_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catequizando',
            name='id',
        ),
        migrations.AddField(
            model_name='catequista',
            name='contra',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catequizando',
            name='id_catequizando',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
