# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_auto_20171102_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catequizando',
            name='fecha_de_bautizo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catequizando',
            name='fecha_nacimiento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
